name: myfirstworkflow
on: [create]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python - pip install --upgrade pip
          pip install pyyaml pandas
      - uses: actions/checkout@v2
      - name: Run Feed generator
        run: |
          python file-editor.py $GITHUB_REPOSITORY
          echo $GITHUB_REPOSITORY
      # - name: push repo
      #   run: |
      #     git config user.name github-actions
      #     git config user.email sachin.kansal456@gmail.com
      #     git checkout -b bot-branch
      #     git add .
      #     git commit -m "adding bot file"
      #     git push --set-upstream origin bot-branch