name: myfirstworkflow
on: [create]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python - pip install --upgrade pip
          pip install pyyaml pandas
      - name: Run Feed generator
        run: |
          python file-editor.py ${{ github.repository }}
          echo ${{ github.repository }}
      - name: push repo
        run: |
          git config --global user.name Sachin Kansal
          git config --global user.email sachin.kansal456@gmail.com
          git checkout -b bot-branch
          git add .
          git commit -m "adding bot file"
          git push --set-upstream origin bot-branch
