name: read-writefrom read-write from read me
on:
  push:
    branches: [release**]
    paths:
      - ./README.md
  workflow_dispatch:

jobs:
  read:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: readfromreadme
        run: |
          cat README.md > ./my-bot-readmefile.txt
          git config --global user.email "bot@gmail.com"
          git config --global user.name "gitbot"
          git checkout -b bot-branch
          git add .
          git commit -m "adding bot file"
          git push
        shell: bash
      #- name: filterfromreadme
      #  run: |
          